In [95]:
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [96]:
value = np.array([-8,-7,-6,-5,-3,-2,2,3,5,6,7,8])
x=1
cero=0
target=[]
salida=[]
value

array([-8, -7, -6, -5, -3, -2,  2,  3,  5,  6,  7,  8])

In [97]:
def definirTarget(i):
    if math.fabs(i)<= 3:
        return x
    else:
        return cero

In [98]:
for i in value:
    target.append(definirTarget(i))

In [99]:
target=np.array(target)
target

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [100]:
x_train, x_test, y_train, y_test = train_test_split(value, target)
x_train, x_test, y_train, y_test

(array([-7,  5, -5, -2,  8,  3, -8,  2, -3]),
 array([-6,  7,  6]),
 array([0, 0, 0, 1, 0, 1, 0, 1, 1]),
 array([0, 0, 0]))

In [101]:
def my_kernel(value):
    for i in value:
        salida.append(i)
    return salida
my_kernel(value)

[-8, -7, -6, -5, -3, -2, 2, 3, 5, 6, 7, 8]